/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apartment_management_system;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Christus
 */
public class AdminDash_Frame extends javax.swing.JFrame {

    /**
     * Creates new form MainApp_Frame
     */
    public AdminDash_Frame() {
        initComponents();
        
        Border all_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        admin_logo.setBorder(all_border);
        
        Border bottom_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
        apartment_frame.setBorder(bottom_border);
        building_frame.setBorder(bottom_border);
        employee_frame.setBorder(bottom_border);
        tenant_frame.setBorder(bottom_border);
        lease_frame.setBorder(bottom_border);
        view_complaint_frame.setBorder(bottom_border);
        logout.setBorder(bottom_border);
        change_apt_frame.setBorder(bottom_border);
        maintenance_frame.setBorder(bottom_border);
        notification_frame.setBorder(bottom_border);
        pay_frame.setBorder(bottom_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        admin_logo = new javax.swing.JLabel();
        apartment_frame = new javax.swing.JLabel();
        building_frame = new javax.swing.JLabel();
        employee_frame = new javax.swing.JLabel();
        tenant_frame = new javax.swing.JLabel();
        lease_frame = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        view_complaint_frame = new javax.swing.JLabel();
        change_apt_frame = new javax.swing.JLabel();
        maintenance_frame = new javax.swing.JLabel();
        notification_frame = new javax.swing.JLabel();
        pay_frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        admin_logo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        admin_logo.setText("    THouses");

        apartment_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        apartment_frame.setText("      Apartment");
        apartment_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apartment_frameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apartment_frameMouseEntered(evt);
            }
        });

        building_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        building_frame.setText("      Building");
        building_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                building_frameMouseClicked(evt);
            }
        });

        employee_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        employee_frame.setText("      Employee");
        employee_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_frameMouseClicked(evt);
            }
        });

        tenant_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        tenant_frame.setText("      Tenant");
        tenant_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenant_frameMouseClicked(evt);
            }
        });

        lease_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lease_frame.setText("      Lease");
        lease_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lease_frameMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        logout.setText("      Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        view_complaint_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        view_complaint_frame.setText("      View Complaint");
        view_complaint_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_complaint_frameMouseClicked(evt);
            }
        });

        change_apt_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        change_apt_frame.setText("      Change Apartment");
        change_apt_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_apt_frameMouseClicked(evt);
            }
        });

        maintenance_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        maintenance_frame.setText("      Maintenance");
        maintenance_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintenance_frameMouseClicked(evt);
            }
        });

        notification_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        notification_frame.setText("      Notification ");
        notification_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_frameMouseClicked(evt);
            }
        });

        pay_frame.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pay_frame.setText("      Payment ");
        pay_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_frameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view_complaint_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lease_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employee_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apartment_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(building_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenant_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(change_apt_frame, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(maintenance_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notification_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pay_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(admin_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(apartment_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(building_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employee_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tenant_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lease_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_complaint_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(change_apt_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maintenance_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notification_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pay_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 675, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void apartment_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apartment_frameMouseClicked
        // TODO add your handling code here:
        //Display Apartment Frame On Mouse Click
        Apartment_Frame apartment = new Apartment_Frame();
        apartment.setVisible(true);
        
    }//GEN-LAST:event_apartment_frameMouseClicked

    private void building_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_building_frameMouseClicked
        // TODO add your handling code here:
        //Display Building Frame On Mouse Click
        Building_Frame building = new Building_Frame();
        building.setVisible(true);
        building.pack();
        
    }//GEN-LAST:event_building_frameMouseClicked

    private void employee_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_frameMouseClicked
        // TODO add your handling code here:
        //Display Employee Frame On Mouse Click
        Employee_Frame employee = new Employee_Frame();
        employee.setVisible(true);
        employee.pack();
        
    }//GEN-LAST:event_employee_frameMouseClicked

    private void tenant_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenant_frameMouseClicked
        // TODO add your handling code here:
        //Display Tenant Frame On Mouse Click
        Tenant_Frame tenant = new Tenant_Frame();
        tenant.setVisible(true);
        tenant.pack();
        
    }//GEN-LAST:event_tenant_frameMouseClicked

    private void apartment_frameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apartment_frameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_apartment_frameMouseEntered

    private void lease_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lease_frameMouseClicked
        // TODO add your handling code here:
        //Display Lease Frame On Mouse Click
        Lease_Frame lease = new Lease_Frame();
        lease.setVisible(true);
        lease.pack();
        
    }//GEN-LAST:event_lease_frameMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        // Dispose of the current frame
        dispose();

        // Create and show the login frame
        Login_Frame login = new Login_Frame();
        login.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void view_complaint_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_complaint_frameMouseClicked
        // TODO add your handling code here:
        View_Complaint_Frame complaint = new View_Complaint_Frame();
        complaint.setVisible(true);
        complaint.pack();
    }//GEN-LAST:event_view_complaint_frameMouseClicked

    private void change_apt_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_apt_frameMouseClicked
        // TODO add your handling code here:
        ChangeApt_Frame change_apt = new ChangeApt_Frame();
        change_apt.setVisible(true);
        change_apt.pack();
    }//GEN-LAST:event_change_apt_frameMouseClicked

    private void maintenance_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenance_frameMouseClicked
        // TODO add your handling code here:
        Maintenance_Frame maintenance = new Maintenance_Frame();
        maintenance.setVisible(true);
        maintenance.pack();
    }//GEN-LAST:event_maintenance_frameMouseClicked

    private void notification_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_frameMouseClicked
        // TODO add your handling code here:
        Notification_Frame notification = new Notification_Frame();
        notification.setVisible(true);
        notification.pack();
    }//GEN-LAST:event_notification_frameMouseClicked

    private void pay_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_frameMouseClicked
        // TODO add your handling code here:
        Pay_Frame pay = new Pay_Frame();
        pay.setVisible(true);
        pay.pack();
    }//GEN-LAST:event_pay_frameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDash_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDash_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDash_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDash_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDash_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_logo;
    private javax.swing.JLabel apartment_frame;
    private javax.swing.JLabel building_frame;
    private javax.swing.JLabel change_apt_frame;
    private javax.swing.JLabel employee_frame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lease_frame;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel maintenance_frame;
    private javax.swing.JLabel notification_frame;
    private javax.swing.JLabel pay_frame;
    private javax.swing.JLabel tenant_frame;
    private javax.swing.JLabel view_complaint_frame;
    // End of variables declaration//GEN-END:variables
}
