/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apartment_management_system;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christus
 */
public class Notification_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Property_Type_Frame
     */
    public Notification_Frame() {
        initComponents();
        
        
        Border bottom_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
        frame_title.setBorder(bottom_border);
        
        //Populate The Building Table
        fillNotificationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        frame_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_temp_name = new javax.swing.JTextField();
        add_notification = new javax.swing.JButton();
        update_notification = new javax.swing.JButton();
        refresh_table = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_subject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        delete_notification = new javax.swing.JButton();
        txt_email_address = new javax.swing.JTextField();
        frame_title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notification_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        frame_title.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        frame_title.setText("     Notification  Frame");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(frame_title, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(frame_title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel1.setText("Template Name:");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel2.setText("Description:");

        txt_temp_name.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txt_temp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_temp_nameActionPerformed(evt);
            }
        });

        add_notification.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        add_notification.setText("Add Notification");
        add_notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_notificationActionPerformed(evt);
            }
        });

        update_notification.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        update_notification.setText("Update Notification");
        update_notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_notificationActionPerformed(evt);
            }
        });

        refresh_table.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        refresh_table.setText("Refresh Table");
        refresh_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_tableActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel3.setText("Subject:");

        txt_subject.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txt_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subjectActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel4.setText("Email Address:");

        delete_notification.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        delete_notification.setText("Delete Notification");
        delete_notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_notificationActionPerformed(evt);
            }
        });

        txt_email_address.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txt_email_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_addressActionPerformed(evt);
            }
        });

        frame_title1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        frame_title1.setText("Notification Template  List");

        notification_table.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        notification_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        notification_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(notification_table);

        txt_description.setColumns(20);
        txt_description.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txt_description.setRows(5);
        jScrollPane2.setViewportView(txt_description);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(add_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(update_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(delete_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(refresh_table, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_subject)
                            .addComponent(txt_email_address)
                            .addComponent(txt_temp_name)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(frame_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(frame_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_temp_name)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh_table, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Define a method to clear text fields
    private void clearTextFields() {
        txt_temp_name.setText("");
        txt_description.setText("");
        txt_subject.setText("");
        txt_email_address.setText("");
    }
    
    //Method To Populate The JList Using The Arraylist in our Notification_Class
    public void fillNotificationTable(){
        Notification_Class notification = new Notification_Class();
        ArrayList<Notification_Class> notificationList = notification.notificationList();
        
        //JTable Columns
        String[] colNames = {"Name", "Description", "Subject", "Email"};
        
        //JTable Rows
        //notificationList.size() = size of the arraylist
        //4 = the number of columns
        Object[][] rows = new Object[notificationList.size()][4];
        
        //add data from the list to the rows
        for(int i = 0; i < notificationList.size(); i++){
            rows[i][0] = notificationList.get(i).getTemplate_Name();
            rows[i][1] = notificationList.get(i).getDescription();
            rows[i][2] = notificationList.get(i).getSubject();
            rows[i][3] = notificationList.get(i).getEmail();
            
            DefaultTableModel model = new DefaultTableModel(rows, colNames);
            notification_table.setModel(model);
            
        }
    }
    
    private void txt_temp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_temp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_temp_nameActionPerformed

    private void update_notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_notificationActionPerformed
        // TODO add your handling code here:
        //EDIT NOTIFICATION
        String temp_name = txt_temp_name.getText();
        String description = txt_description.getText();
        String subject = txt_subject.getText();
        String email = txt_email_address.getText();
        
        Notification_Class notification = new Notification_Class(temp_name, description, subject, email);
        
        if (!temp_name.isBlank() && !description.isBlank() && !subject.isBlank() && !email.isBlank()) {
            if(new Notification_Class().editNotification(notification)){
                JOptionPane.showMessageDialog(null, "Notification Updated Successfully", "Update Notification", 1);
                clearTextFields();
            }else{
                JOptionPane.showMessageDialog(null, "Operation Failed", "Update Notification", 1);
            }
            clearTextFields();  
        } else {
            JOptionPane.showMessageDialog(null, "All Fields Must Be Empty", "Empty Field", 2);
        }


    }//GEN-LAST:event_update_notificationActionPerformed

    private void add_notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_notificationActionPerformed
        // TODO add your handling code here:
        //ADD NOTIFICATION
        String temp_name = txt_temp_name.getText();
        String description = txt_description.getText();
        String subject = txt_subject.getText();
        String email = txt_email_address.getText();
        
        Notification_Class notification = new Notification_Class(temp_name, description, subject, email);
        
        if (!temp_name.isBlank() && !description.isBlank() && !subject.isBlank() && !email.isBlank()) {
            if(new Notification_Class().addNotification(notification)){
                JOptionPane.showMessageDialog(null, "Notification Added Successfully", "Add Notification", 1);
                clearTextFields();
            }else{
                JOptionPane.showMessageDialog(null, "Operation Failed", "Add Notification", 1);
            }
            clearTextFields();  
        } else {
            JOptionPane.showMessageDialog(null, "All Fields Must Be Empty", "Empty Field", 2);
        }
    }//GEN-LAST:event_add_notificationActionPerformed

    private void txt_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subjectActionPerformed

    private void delete_notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_notificationActionPerformed
        // TODO add your handling code here:
        //DELETE NOTIFICATION
        String temp_name = txt_temp_name.getText();
        
        Notification_Class notification = new Notification_Class(temp_name, "", "", "");
        
        if (!temp_name.isBlank()) {
            
            int confirm = JOptionPane.showConfirmDialog(null, "Confirm Delete?", "Delete Notification", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                if(new Notification_Class().deleteNotification(notification)){
                    JOptionPane.showMessageDialog(null, "Notification Deleted Successfully", "Delete Notification", 1);
                    clearTextFields();
                }else{
                    JOptionPane.showMessageDialog(null, "Operation Failed", "Delete Notification", 2);
                }
                clearTextFields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "All Fields Must Be Empty", "Empty Field", 2);
        }
        
    }//GEN-LAST:event_delete_notificationActionPerformed

    private void txt_email_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_addressActionPerformed

    private void refresh_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_tableActionPerformed
        // TODO add your handling code here:
        fillNotificationTable();
    }//GEN-LAST:event_refresh_tableActionPerformed

    private void notification_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_tableMouseClicked
        // TODO add your handling code here:
        //Fill The Form Fields With The Selected Building Data
        int selectedRowIndex = notification_table.getSelectedRow();
        txt_temp_name.setText(notification_table.getValueAt(selectedRowIndex, 0).toString());
        txt_description.setText(notification_table.getValueAt(selectedRowIndex, 1).toString());
        txt_subject.setText(notification_table.getValueAt(selectedRowIndex, 2).toString());
        txt_email_address.setText(notification_table.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_notification_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notification_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_notification;
    private javax.swing.JButton delete_notification;
    private javax.swing.JLabel frame_title;
    private javax.swing.JLabel frame_title1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable notification_table;
    private javax.swing.JButton refresh_table;
    private javax.swing.JTextArea txt_description;
    private javax.swing.JTextField txt_email_address;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextField txt_temp_name;
    private javax.swing.JButton update_notification;
    // End of variables declaration//GEN-END:variables
}
