/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apartment_management_system;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christus
 */
public class Tenant_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Property_Type_Frame
     */
    public Tenant_Frame() {
        initComponents();
        
        
        Border bottom_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
        frame_title.setBorder(bottom_border);
        
        fillJTableWithTenantData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        frame_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_textfield = new javax.swing.JTextField();
        fname_textfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        add_tenant = new javax.swing.JButton();
        update_tenant = new javax.swing.JButton();
        refresh_table = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lname_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phone_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        pwd_textfield = new javax.swing.JPasswordField();
        delete_tenant = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        address_textfield = new javax.swing.JTextField();
        zipcode_textfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        frame_title.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        frame_title.setText("    Tenant  Frame");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frame_title, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(frame_title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel1.setText("ID: ");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel2.setText("FirstName: ");

        id_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        id_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textfieldActionPerformed(evt);
            }
        });

        fname_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        fname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_textfieldActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        add_tenant.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        add_tenant.setText("Add Tenant");
        add_tenant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_tenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_tenantActionPerformed(evt);
            }
        });

        update_tenant.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        update_tenant.setText("Update Tenant");
        update_tenant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_tenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_tenantActionPerformed(evt);
            }
        });

        refresh_table.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        refresh_table.setText("Refresh Table");
        refresh_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_tableActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel3.setText("LastName: ");

        lname_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lname_textfieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel4.setText("Password: ");

        phone_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        phone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_textfieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel5.setText("Phone: ");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel6.setText("Email: ");

        email_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        delete_tenant.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        delete_tenant.setText("Delete Tenant");
        delete_tenant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_tenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_tenantActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel7.setText("Address:");

        address_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        address_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_textfieldActionPerformed(evt);
            }
        });

        zipcode_textfield.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        zipcode_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcode_textfieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel8.setText("ZipCode: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(update_tenant)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname_textfield)
                            .addComponent(lname_textfield)
                            .addComponent(phone_textfield)
                            .addComponent(email_textfield)
                            .addComponent(pwd_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_textfield)
                            .addComponent(zipcode_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(delete_tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add_tenant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refresh_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_textfield)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pwd_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zipcode_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh_table, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(delete_tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Define a method to clear text fields
    private void clearTextFields() {
        id_textfield.setText("");
        fname_textfield.setText("");
        lname_textfield.setText("");
        pwd_textfield.setText("");
        phone_textfield.setText("");
        email_textfield.setText("");
        address_textfield.setText("");
        zipcode_textfield.setText("");
    }
    
    //Method To Populate The JTable With The Tenant Data Using The Arraylist We Created In Our Tenant_Class
    //And Also To Fill The Form With The Selected Tenant's Data
    public void fillJTableWithTenantData(){
        Tenant_Class tenant = new Tenant_Class();
        ArrayList<Tenant_Class> tenantList = tenant.tenantList();
        
        //JTable Columns
        String[] colNames = {"TenantID", "FirstName", "LastName", "Phone", "Email", "Address", "ZipCode"};
        
        //JTable Rows
        //tenantList.size() = size of the arraylist
        //7 = the number of columns
        Object[][] rows = new Object[tenantList.size()][7];
        
        //add data from the list to the rows
        for(int i = 0; i < tenantList.size(); i++){
            rows[i][0] = tenantList.get(i).getId();
            rows[i][1] = tenantList.get(i).getFirstName();
            rows[i][2] = tenantList.get(i).getLastName();
            rows[i][3] = tenantList.get(i).getPhone();
            rows[i][4] = tenantList.get(i).getEmail();
            rows[i][5] = tenantList.get(i).getAddress();
            rows[i][6] = tenantList.get(i).getZipcode();
            
            DefaultTableModel model = new DefaultTableModel(rows, colNames);
            jTable.setModel(model);
            
            jTable.getColumnModel().getColumn(0).setPreferredWidth(45);//Set A Preferred Width For The Id Column
            jTable.getColumnModel().getColumn(1).setPreferredWidth(25);//Set A Preferred Width For The FirstName Column
            jTable.getColumnModel().getColumn(2).setPreferredWidth(25);//Set A Preferred Width For The LastName Column
            jTable.getColumnModel().getColumn(3).setPreferredWidth(28);//Set A Preferred Width For The LastName Column
            jTable.getColumnModel().getColumn(6).setPreferredWidth(25);//Set A Preferred Width For The LastName Column
            
        }
        
    }
    
    
    
    private void id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textfieldActionPerformed

    private void fname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_textfieldActionPerformed

    private void update_tenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_tenantActionPerformed
        // TODO add your handling code here:
        //UPDATE TENANT
        String idText = id_textfield.getText();
        if (!idText.isBlank() && idText.matches("\\d+")) {
            try {
                int id = Integer.parseInt(idText);
                String firstname = fname_textfield.getText();
                String lastname = lname_textfield.getText();
                char[] passwordChars = pwd_textfield.getPassword();
                String password = new String(passwordChars);
                String phone = phone_textfield.getText();
                String email = email_textfield.getText();
                String address = address_textfield.getText();
                String zipcode = zipcode_textfield.getText();

                if (!firstname.isBlank() && !lastname.isBlank() && !password.isBlank() && !phone.isBlank() && !email.isBlank() && !address.isBlank() && !zipcode.isBlank()) {
                    Tenant_Class type = new Tenant_Class(id, firstname, lastname, password, phone, email, address, zipcode);

                    if (type.executeQueryType("edit", type)) {
                        JOptionPane.showMessageDialog(null, "Tenant Updated Successfully", "Edit Tenant", 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Try Again, Operation Failed", "Edit Tenant", 2);
                    }
                    // Clear the text fields in any case (whether the edit operation succeeds or not).
                    clearTextFields();
                } else {
                    JOptionPane.showMessageDialog(null, "All Fields Must Not Be Empty", "Empty Field", 2);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid ID. Please enter a valid number for the ID.", "Invalid ID", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter The ID You Wish To Update And Fill All Fields", "Empty Field", 2);
        }
        // Clear the text fields in any case (whether the edit operation succeeds or not).
        clearTextFields();

    }//GEN-LAST:event_update_tenantActionPerformed

    private void add_tenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_tenantActionPerformed
        // TODO add your handling code here:
        //ADD TENANT
        String firstname = fname_textfield.getText();
        String lastname = lname_textfield.getText();
        char[] passwordChars = pwd_textfield.getPassword();
        String password = new String(passwordChars);
        String phone = phone_textfield.getText();
        String email = email_textfield.getText();
        String address = address_textfield.getText();
        String zipcode = zipcode_textfield.getText();

        if (firstname.isBlank() || lastname.isBlank() || password.isBlank() || phone.isBlank() || email.isBlank() || address.isBlank() || zipcode.isBlank()) {
            JOptionPane.showMessageDialog(null, "Fill All Fields Except The ID", "Empty Field", 2);
            // Clear the text fields using the clearTextFields method
            clearTextFields();
        } else {
            Tenant_Class type = new Tenant_Class(0, firstname, lastname, password, phone, email, address, zipcode);

            if (type.executeQueryType("add", type)) {
                JOptionPane.showMessageDialog(null, "New Tenant Added Successfully", "Add Tenant", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Try Again, Operation Failed", "Add Tenant", 2);
            }

            // Clear the text fields using the clearTextFields method
            clearTextFields();
        }
    }//GEN-LAST:event_add_tenantActionPerformed

    private void lname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_textfieldActionPerformed

    private void phone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_textfieldActionPerformed

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    private void delete_tenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_tenantActionPerformed
        // TODO add your handling code here:
        //DELETE TENANT
        String idText = id_textfield.getText();
        if (!idText.isBlank() && idText.matches("\\d+")) {
            int id = Integer.parseInt(idText);
            Tenant_Class type = new Tenant_Class(id, "", "", "", "", "", "", "");

            int confirm = JOptionPane.showConfirmDialog(null, "Confirm Remove?", "Remove Employee", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (type.executeQueryType("remove", type)) {
                    JOptionPane.showMessageDialog(null, "Tenant Removed Successfully", "Remove Tenant", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again, Operation Failed", "Remove Tenant", 2);
                }
            }
            // Clear the text fields using the clearTextFields method
            clearTextFields();
        } else {
            JOptionPane.showMessageDialog(null, "Enter a Valid ID to Delete", "Invalid Input", 2);
        }
        
    }//GEN-LAST:event_delete_tenantActionPerformed

    private void address_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_textfieldActionPerformed

    private void zipcode_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcode_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcode_textfieldActionPerformed

    private void refresh_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_tableActionPerformed
        // TODO add your handling code here:
        fillJTableWithTenantData();
    }//GEN-LAST:event_refresh_tableActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        //Fill The Form With The Selected Tenants Data
        int selectedRowIndex = jTable.getSelectedRow();
        id_textfield.setText(jTable.getValueAt(selectedRowIndex, 0).toString());
        fname_textfield.setText(jTable.getValueAt(selectedRowIndex, 1).toString());
        lname_textfield.setText(jTable.getValueAt(selectedRowIndex, 2).toString());
        phone_textfield.setText(jTable.getValueAt(selectedRowIndex, 3).toString());
        email_textfield.setText(jTable.getValueAt(selectedRowIndex, 4).toString());
        address_textfield.setText(jTable.getValueAt(selectedRowIndex, 5).toString());
        zipcode_textfield.setText(jTable.getValueAt(selectedRowIndex, 6).toString());
    }//GEN-LAST:event_jTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tenant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tenant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tenant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tenant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tenant_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_tenant;
    private javax.swing.JTextField address_textfield;
    private javax.swing.JButton delete_tenant;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JTextField fname_textfield;
    private javax.swing.JLabel frame_title;
    private javax.swing.JTextField id_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField lname_textfield;
    private javax.swing.JTextField phone_textfield;
    private javax.swing.JPasswordField pwd_textfield;
    private javax.swing.JButton refresh_table;
    private javax.swing.JButton update_tenant;
    private javax.swing.JTextField zipcode_textfield;
    // End of variables declaration//GEN-END:variables
}
